### ISSUE TITLE
SMF does not properly map default path to UPF destination.

### ISSUE THREAD

**Issue by aviweit** [free5gc/smf#40]
SMF does not properly map default path to UPF destination.

Environment:

* free5gc docker compose v3.06
* smf: v1.0.1

I am using the below `uerouting.yaml` and can see that SMF states that it builds a datapath to UPF-C1: `New default data path (gNB1 to UPF-C1)` but the path destination is UPF-C2 and not UPF-C1 as it should be. I validated that the 3rd node ip `10.100.200.6` indicated in the attached logs, is of UPF-C2.

Looking into it more, I can see that the method `getAllPathByNodeName` uses a recursion in which I suspect that `allPaths` get changed during the recursion stack even-though it is not being explicitly set.

Please find attached SMF logs. If needed, I can send smfcfg.yaml.

Thanks.

```
ueRoutingInfo: # the list of UE routing information
  UE-gNB-1-1: # Group Name
    members:
    - imsi-208930000000002 # Subscription Permanent Identifier of the UE
    - imsi-208930000000001 # Subscription Permanent Identifier of the UE
    topology:
    # Network topology for this group (Uplink: A->B, Downlink: B->A)
    # default path derived from this topology
    # node name should be consistent with smfcfg.yaml
      - A: gNB1
        B: UPF-R1

      - A: UPF-R1
        B: UPF-T1

      - A: UPF-R1
        B: UPF-T2

      - A: UPF-T1
        B: UPF-C1

      - A: UPF-T1
        B: UPF-C2

      - A: UPF-T2
        B: UPF-C2

      - A: UPF-T2
        B: UPF-C3

      - A: UPF-T2
        B: UPF-C4

    specificPath:
      - dest: 60.61.0.0/16 # the destination IP address on Data Network (DN)
        # the order of UPF nodes in this path. We use the UPF's name to represent each UPF node.
        # The UPF's name should be consistent with smfcfg.yaml
        path: [UPF-R1, UPF-T1, UPF-C1]
```

```
smf       | 2022-01-16T13:58:11Z [DEBU][SMF][Init] gNB1 is AN
smf       | 2022-01-16T13:58:11Z [DEBU][SMF][Init] UPF-C1 is Anchor UPF
smf       | 2022-01-16T13:58:11Z [DEBU][SMF][Init] UPF-C2 is Anchor UPF
smf       | 2022-01-16T13:58:11Z [DEBU][SMF][Init] UPF-C3 is Anchor UPF
smf       | 2022-01-16T13:58:11Z [DEBU][SMF][Init] UPF-C4 is Anchor UPF
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T1]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T1 UPF-C1]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] all path: map[0:[UPF-R1 UPF-T1 UPF-C1]]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T1 UPF-C2]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T2]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T2 UPF-C2]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T2 UPF-C3]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][Init] current path: [gNB1 UPF-R1 UPF-T2 UPF-C4]
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][CTX] New default data path (gNB1 to UPF-C1):
smf       | 2022-01-16T13:58:11Z [TRAC][SMF][CTX] DataPath Meta Information
smf       | Activated: false
smf       | IsDefault Path: false
smf       | Has Braching Point: false
smf       | Destination IP:
smf       | Destination Port:
smf       | DataPath Routing Information
smf       | 1th Node in the Path
smf       | Current UPF IP: 10.100.200.5
smf       | Previous UPF IP: None
smf       | Next UPF IP: 10.100.200.8
smf       | 2th Node in the Path
smf       | Current UPF IP: 10.100.200.8
smf       | Previous UPF IP: 10.100.200.5
smf       | Next UPF IP: 10.100.200.6
smf       | 3th Node in the Path
smf       | Current UPF IP: 10.100.200.6
smf       | Previous UPF IP: 10.100.200.8
smf       | Next UPF IP: None
```
