### ISSUE TITLE
Missing IE Forwarding Parameters

### ISSUE THREAD

**Issue by louisroyer** [free5gc/smf#55]
In the PFCP Session Establishment Request message, the 2nd `Create FAR` IE is missing the mandatory (because `Apply Action` is present with the field `FORW` set to 1) `Forwarding Parameters` IE.

Wireshark screenshot:
![2022-06-23T15:14:42,696456940+02:00](https://user-images.githubusercontent.com/55180044/175307416-95cdb72c-d429-4130-a1b1-3051164e450f.png)
 
I use the following config:
`smf-config.yaml`
```yaml
info:
  version: 1.0.2
  description: SMF initial local configuration

configuration:
  smfName: SMF1
  sbi:
    scheme: http
    registerIPv4: smf1.sbi-net # IP used to register to NRF
    bindingIPv4: 10.0.211.3  # IP used to bind the service
    port: 8000
    tls:
      key: config/TLS/smf.key
      pem: config/TLS/smf.pem
  serviceNameList:
    - nsmf-pdusession
    - nsmf-event-exposure
    - nsmf-oam
  snssaiInfos:
    - sNssai:
        sst: 1
        sd: 010203
      dnnInfos:
        - dnn: sliceA
          dns: 
            ipv4: 10.0.224.3
            ipv6: 2001:4860:4860::8888
  plmnList:
    - mcc: "001"
      mnc: "01"

  pfcp:
    addr: 10.0.210.2
  userplaneInformation:
    upNodes:
      ran-area1-1:
        type: AN


      upf-mec-area1:
        type: UPF
        nodeID: 10.0.213.3
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: sliceA
        interfaces:
          - interfaceType: N3
            endpoints:
              - 10.0.201.3
            networkInstance: sliceA
          - interfaceType: N9
            endpoints:
              - 10.0.215.2
            networkInstance: sliceA


      upf-sliceA:
        type: UPF
        nodeID: 10.0.210.3
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: sliceA
                pools:
                  - cidr: 10.0.222.0/24
        interfaces:
          - interfaceType: N9
            endpoints:
              - 10.0.216.2
            networkInstance: sliceA
    links:
      - A: ran-area1-1
        B: upf-mec-area1
      - A: upf-mec-area1
        B: upf-sliceA

  nrfUri: http://nrf.sbi-net:8000 
  ulcl: true

logger:
  SMF:
    debugLevel: trace
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PFCP:
    debugLevel: trace
    ReportCaller: false
```
`ue-routing.yaml`
```yaml
info:
  version: 1.0.1
  description: Routing information for UE

ueRoutingInfo: # the list of UE routing information

  MEH:
    members:
      - imsi-001010000000000
      - imsi-001010000000001

    topology:
      - A: ran-area1-1
        B: upf-mec-area1
      - A: upf-mec-area1
        B: upf-sliceA
    specificPath:
      - dest: 10.0.224.3/32
        path: [upf-mec-area1, upf-mec-area1]
      - dest: 10.0.222.0/24
        path: [upf-mec-area1, upf-mec-area1]
```
